//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDFrame.FrameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrameService.IModuleAuth")]
    public interface IModuleAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAuth/ModuleAuthentication", ReplyAction="http://tempuri.org/IModuleAuth/ModuleAuthenticationResponse")]
        DataModel.UserInfo ModuleAuthentication(string UID, string PWD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuleAuthChannel : HDFrame.FrameService.IModuleAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuleAuthClient : System.ServiceModel.ClientBase<HDFrame.FrameService.IModuleAuth>, HDFrame.FrameService.IModuleAuth {
        
        public ModuleAuthClient() {
        }
        
        public ModuleAuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuleAuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataModel.UserInfo ModuleAuthentication(string UID, string PWD) {
            return base.Channel.ModuleAuthentication(UID, PWD);
        }
    }
}
